Fix build with Linux 6.8
With commit
https://github.com/torvalds/linux/commit/57f22c8dab6b266ae36b89b073a4a33dea71e762
strlcpy has been removed in favor of strscpy. Thus giving us build error
such as nf_conntrack_rtsp.c: error: implicit declaration of function
strlcpy.

First reported on Gentoo Linux, please reffer:
https://bugs.gentoo.org/928590

Signed-off-by: Brahmajit Das <brahmajit.xyz@gmail.com>